# Generated by Django 3.2.9 on 2021-11-27 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=23)),
                ('password', models.CharField(max_length=6)),
                ('date', models.DateField()),
            ],
        ),
    ]
