# Generated by Django 3.2.9 on 2021-12-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogs',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('auther', models.CharField(max_length=12)),
                ('tital', models.CharField(max_length=12)),
                ('containt', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='contact',
        ),
    ]
