# Generated by Django 3.2.9 on 2021-12-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_rename_blogs_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
    ]
